language: php

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""
    global:
        - secure: fZrUPsGBBphM4MY5egBm0noGgZ8lbklQ9C41KpOu1JHPi9LkwLsnBvGwCSJvU6IHJiBY+tDmu3vDob+BSNJzWfJk3z1h+A1+esdA2NUPZGIX13iSGn1WbbTYmjxoJlilQzy5E7gRB9s2n9VoFFwqMjv0u7of9r/6jxAMIBY2dk0Kk3GJTp54pB7eUXPQ5sufPqTdagfFDYcqV4c3byDzEh0eg4ibsGK1s3vTxNMhoiYvPkrlcQuYSZ7KSEzYJ5S8kO4DkVkKSPipORkjjBQ9w8SK59g9nkHfjrnCo7sLwc+iDOvtmTbB5+rf6Ex+z6rfQIjyqWwfkNU7r8qb3gLr5rRgPhw1ew7WOj/3WJT8PEafgOhPN6Jn70lNUdGGVzI9tQYwWqE+R4uevIYSGe/F3NZoROYVI4B0pV0hLOm/JFq/9oTMMqH+LTpNMLLNEyAfCCIch9lB2FtloTMpGOYvZdhCL+74dgVP8i7hWkr0rpmtKhPXL9wCkFj80pjlepy0a8crX+uGn0IEOm9HYHVgLgdhuuL4KLh5hepgRCM71NVAXnwz2WYE8N8x1S74nRwNQuyyjfPlv56F89u7ONdTm9h65BzAAKTlS4+rHJhmcTbEthQUXMPCAw76ohcH1KmVgmw7pe37/yHl8SQK1ai1kLEenPkPP+V5QqidWKNRtl8=
        - secure: J2SId+AD9miW/CdY0czxgb7/yGrP8wm9Bteu48XwMq9Tn3/TqFpRSG+SYEDQMwsBqCjIakvMoHQEEHb/Puqk6PfaVAaoYDmNyp4AmEGk9YLODLAREyG0rTTHFrOt178qs+tCT3J4W+unVlAt041rYtlxYC8d+s675vAuesHBPAc8nB+7sQkdOINAkGndXMAjWQ+4ToNt11QAvTAgVHguhDSnnS0koMujbPQO/U/646upoSFSye2C/U7OWm7HY+vE8Kov1fNuynNZ0x1dIQtg0GBK0eOuuYInQfEs9TsmhTxKOmplZAat0ufySEo4KTC/AxS1s6RGCzhYU3ZkGO5Xe/ImwbxMswICnb73szmLgeP94Z01hE7MLU1kk4N/hBd7YGvzNk2KYSxHmhVStsoZ7HI7KeE7KhOXHh2rKuB/m0ly6QWMmb8RjSQBWbSrZVFKZ+XxyRPagAGbm85JynewuCwbNZAxef22IB3VqNMuxQqEjaHXdFBz59QcGFxR17X8fs5y6ETiE2yLyTQC8fWFd0jl/Wk38vx1v9cgGAaHiKKt2ZRH/0TKA/6UgnSnyXmLQ+Vk3vzQcDhedYDP86Tj+4LQC/AV+d4QjzTBj4xf00W8c3GQQnj+CndeLgvkMfowRyDJfHWZBph3HyKlb2LbAMAkwIKkyrh1wVVjvDCOWIA=
        - secure: C7/jtsLcZWt8u7y4EvhXG508ah2hpBs0uF1ftf1+y1+HiuIlsTaVlicfMUMjyrGprOgUW+BsKaL7SHPiCZEjg8NRrfRxO1xcBUK93he6grwIa2836R63kUS1SY8c7/5BoOgvRZTeZ/sfE7OzI9BfrcW5S4FvMY2hhFv7Zm0FMnUG8uw3n1k/D3tP6hUdBDLsOYWdoJAWErHW5ZLGbarCfiWpo6X/0XZvgBr0As639qZt0bUpbabsF3zmu5N5jN8aVAJcF+b9iCJhqEXELtpnFDpfdv54gJRaEFguoS6cqowitL+4z6GLMI9p3V8eyc/eURkLPA188A896I53UvmVM7IYSEM1rezr8hSaMKvTJy1WNqvaZcUXdwOBhRkfADrZ44n7qoRZTOXUvQ5GcFrtMs0x0SC3t4wd4OUCJT3M6lF3539IJrULFALhtj/w4sALGFpiDTffydbOaxtDTFoCuXu6Z1AmiYhaCFrN5a4CT5YYpS7U35309d0nq1T4sQ42S+SRSinRpazVLm0VR9iCdQk67432LmttdEa7hFlUoIwOEkJzJA8omE+8miflAAQWRwUfflg8Fs9q1rzphEV8YMxKQY4i2zIbVPvr3SVxSi1qlzBz+J6b/HMKS5G6PWbyKJQUhuvfZyde0Xi79H4a4CJl2jGW8QZ5sX/x3zy0U38=
        - secure: rOnjuEHh0wHPkFxQKsQVLjcUQV5N97E5a3Tq/034yu1goi+FXN8dipIpnCbAejJp634R0DoApE9WiFXkz5hcARpNHLWcZkFUvIwl5fjrZFc2GGaryDWf6qRnC00k5OGEGxFdc51/VyCIOCpbj/HnDpBmAWcxGuQPROB+itpIo3Ux/m9ftmxNZ8njPsZ3aGUpqOUL4EOUxWpMP/ANcLGU8RsVz0i1hj61NBzYwE291C0Mnrf0GRpKhGlDhs0kg31B+rwrtkZ2hMAPBoHp1g5fKJvEFqWmy8Tk846HsN9z4vRGbOrfrb8grLxRTaE7Z0+M8fo3vRvtcGq6QVeKsEZD6Xjr3yuiGDtThtkAQlzPZcjPzSRGgUHXYN8lnSEtsR2mmGPe1dKQH3oTGcJJLICv35mnlezqptGF8+zDq+T11JB7x7IPs0qmpde/qPpRL78C8gPNXIDvno7DMDQ7x8+4HiH98U4f1DfUWa4D886QdjMBqocDmlWnHJWWpq4u/wg6sduJs9DLau0cepS/MTGP2ecLKgRnLXwxWWegeRnPWXWGRMZT2i61OVZyYKF9bOQwhjeGq92RMphxzr/MCXTR7mGyrkN+RGAAuEsYAG89Dl9pOzME0sMYHY0SJjx4TwNux9OhF9eiy3XQyd3RbBHcau+rB5fUtq0fD8pY0irL4zs=

jobs:
    allow_failures:
        - php: nightly

php:
    - nightly
    - 8.0
    - 7.4
    - 7.3
    - 7.2
    - 7.1

before_script:
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - phpenv config-rm xdebug.ini
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - composer test

after_script:
    - composer upload-coverage
